server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul
    username: jwt
    password: jwt

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%method:line%line] - %msg%n"
  level:
    org:
      springframework: error
    it:
      aKMa: DEBUG
